databases:
  - name: postgres
    ipAllowList: []

services:
  - type: web
    name: rails
    env: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec rails s'
    envVars:
      - key: da6394a6f23cdc9570585ef7341391a9
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
  - type: redis
    name: redis
    ipAllowlist: []
    plan: free
    maxmemoryPolicy: noeviction
