databases:
  - name: postgres
    ipAllowlist: []

services:
  - type: web
    name: rails
    env: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec rails s'
    envVars:
      - key: RAILS8MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
  - type: redis
    name: redis
    env: redis
    ipAllowlist: []
    plan: free
    maxmemoryPolicy: noeviction
